import IsolateApi from './isolate-api.ts'
export type { IsolateApi }
export const IO_PATH = '.io.json'
import {
  IsolateApiSchema,
  IsolateReturn,
  Outcome,
  Params,
  PID,
  PierceRequest,
  Request,
  SolidRequest,
  UnsequencedRequest,
} from './api/web-client.types.ts'
import FS from '@/git/fs.ts'
import type DB from '@/db.ts'
import type Executor from '@/exe/exe.ts'

/** Artifact Context, including the db and executor */
export type C = { db: DB; exe: Executor }

export type IsolateFunction =
  | (() => unknown | Promise<unknown>)
  | ((...args: [Params]) => unknown | Promise<unknown>)
  | ((...args: [Params, IsolateApi]) => unknown | Promise<unknown>)

export type IsolateFunctions = {
  [key: string]: IsolateFunction
}
export type IsolateLifecycle = {
  '@@mount': (api: IsolateApi) => Promise<IsolateReturn> | IsolateReturn
  '@@unmount'?: (api: IsolateApi) => Promise<IsolateReturn> | IsolateReturn
}
export type Isolate = {
  api: IsolateApiSchema
  functions: IsolateFunctions
  lifecycles?: IsolateLifecycle
}

export type Reply = SolidReply | MergeReply
export type Poolable = Request | Reply

export type EffectRequest = {
  target: PID
  /**
   * The hash of the function that was called, to ensure repeatability
   */
  fingerprint: string
  sequence: number
}
export type SolidReply = {
  target: PID
  sequence: number
  outcome: Outcome
}
export type MergeReply = SolidReply & {
  /**
   * Where did this merge reply come from?
   */
  source: PID
  /**
   * What is the commit that solidified this merge reply?
   */
  commit: string
}
export type IsolatePromise = {
  outcome?: Outcome
  request: UnsequencedRequest
  resolve?: (value: unknown) => void
  reject?: (error: Error) => void
}
export type Solids = {
  commit: string
  exe?: { request: SolidRequest; sequence: number }
  branches: number[]
  replies: MergeReply[]
  deletes: { pid: PID; commit: string }[]
}
export type Branched = {
  /** The first request in the new branch */
  origin: SolidRequest
  /** The branch PID that needs to be created in /.git/refs */
  pid: PID
  /** The head of the new branch that needs to be created in /.git/refs */
  head: string
}
export type ExeResult = ExeSettled | ExePending
type ExeSettled = {
  settled: {
    reply: SolidReply
    /**
     * The last filesystem that was modified during the execution run.  The FS
     * might have been bumped forwards if accumulations occurred.
     */
    fs: FS
  }
  /** If this is a side effect request, this is the lock held by for it */
  effectsLock?: Deno.KvEntry<string>
}
type ExePending = {
  pending: Pending
  /** If this is a side effect request, this is the lock held by for it */
  effectsLock?: Deno.KvEntry<string>
}
export type Pending = {
  /** The commit that caused the requests to be generated */
  commit: string
  /** The requests that were generated by the latest round of execution */
  requests: UnsequencedRequest[]
}

export const isRequest = (poolable: Poolable): poolable is Request => {
  return 'proctype' in poolable
}
export const isMergeReply = (poolable: Reply): poolable is MergeReply => {
  return 'commit' in poolable
}
/**
 * Messages that go on the queue are one of four types.  Each on is an operation
 * that will result in a new commit, atomically.  Each operation is able to
 * detect when it is a duplicate task due to duplicate message delivery.  Each
 * task will continue to retry until it is successful, as long as its check for
 * duplication reassures it to keep trying.
 */
export type QueueMessage = QueuePool | QueueExe | QueueBranch | QueueReply

export type QueuePool = {
  pierce: PierceRequest
}
export type QueueExe = {
  request: SolidRequest
  commit: string
  sequence: number
}
export type QueueBranch = {
  parentCommit: string
  parentPid: PID
  sequence: number
}
export type QueueReply = {
  reply: MergeReply
}
export const isQueuePool = (m: QueueMessage): m is QueuePool => {
  return 'pierce' in m
}
export const isQueueExe = (m: QueueMessage): m is QueueExe => {
  return 'request' in m
}
export const isQueueBranch = (m: QueueMessage): m is QueueBranch => {
  return 'parentPid' in m
}
export const isQueueReply = (m: QueueMessage): m is QueueReply => {
  return 'reply' in m
}

export * from './api/web-client.types.ts'
