// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/account/index.tsx";
import * as $5 from "./routes/account/manage.ts";
import * as $6 from "./routes/account/upgrade.ts";
import * as $7 from "./routes/api/comments.ts";
import * as $8 from "./routes/api/items/[id]/comments.ts";
import * as $9 from "./routes/api/items/[id]/index.ts";
import * as $10 from "./routes/api/items/[id]/vote.ts";
import * as $11 from "./routes/api/items/index.ts";
import * as $12 from "./routes/api/me/notifications.ts";
import * as $13 from "./routes/api/me/votes.ts";
import * as $14 from "./routes/api/stripe-webhooks.ts";
import * as $15 from "./routes/api/users/[login]/index.ts";
import * as $16 from "./routes/api/users/[login]/items.ts";
import * as $17 from "./routes/api/users/index.ts";
import * as $18 from "./routes/blog/[slug].tsx";
import * as $19 from "./routes/blog/index.tsx";
import * as $20 from "./routes/dashboard/index.tsx";
import * as $21 from "./routes/dashboard/stats.tsx";
import * as $22 from "./routes/dashboard/users.tsx";
import * as $23 from "./routes/feed.ts";
import * as $24 from "./routes/index.tsx";
import * as $25 from "./routes/items/[id].tsx";
import * as $26 from "./routes/notifications/[id].ts";
import * as $27 from "./routes/notifications/index.tsx";
import * as $28 from "./routes/pricing.tsx";
import * as $29 from "./routes/submit.tsx";
import * as $30 from "./routes/users/[login].tsx";
import * as $$0 from "./islands/Chart.tsx";
import * as $$1 from "./islands/CommentsList.tsx";
import * as $$2 from "./islands/ItemsList.tsx";
import * as $$3 from "./islands/NotificationsList.tsx";
import * as $$4 from "./islands/UsersTable.tsx";
import * as $$5 from "./islands/VoteButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/account/index.tsx": $4,
    "./routes/account/manage.ts": $5,
    "./routes/account/upgrade.ts": $6,
    "./routes/api/comments.ts": $7,
    "./routes/api/items/[id]/comments.ts": $8,
    "./routes/api/items/[id]/index.ts": $9,
    "./routes/api/items/[id]/vote.ts": $10,
    "./routes/api/items/index.ts": $11,
    "./routes/api/me/notifications.ts": $12,
    "./routes/api/me/votes.ts": $13,
    "./routes/api/stripe-webhooks.ts": $14,
    "./routes/api/users/[login]/index.ts": $15,
    "./routes/api/users/[login]/items.ts": $16,
    "./routes/api/users/index.ts": $17,
    "./routes/blog/[slug].tsx": $18,
    "./routes/blog/index.tsx": $19,
    "./routes/dashboard/index.tsx": $20,
    "./routes/dashboard/stats.tsx": $21,
    "./routes/dashboard/users.tsx": $22,
    "./routes/feed.ts": $23,
    "./routes/index.tsx": $24,
    "./routes/items/[id].tsx": $25,
    "./routes/notifications/[id].ts": $26,
    "./routes/notifications/index.tsx": $27,
    "./routes/pricing.tsx": $28,
    "./routes/submit.tsx": $29,
    "./routes/users/[login].tsx": $30,
  },
  islands: {
    "./islands/Chart.tsx": $$0,
    "./islands/CommentsList.tsx": $$1,
    "./islands/ItemsList.tsx": $$2,
    "./islands/NotificationsList.tsx": $$3,
    "./islands/UsersTable.tsx": $$4,
    "./islands/VoteButton.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
