// deno-fmt-ignore-file
// deno-lint-ignore-file

// Copyright Joyent and Node contributors. All rights reserved. MIT license.
// Taken from Node 18.8.0
// This file is automatically generated by "node/_tools/setup.ts". Do not modify this file manually

import fixtures from './fixtures.js';

const {
  fixturesDir,
  path,
  fileURL,
  readSync,
  readKey,
} = fixtures;

export {
  fixturesDir,
  path,
  fileURL,
  readSync,
  readKey,
};
